file.manager.project.directory=D:/Workspace/CTBCTW/BackEnd/gradle/root-project/applications/ctbctw/z-los-artifact/z_liquibase_v1
file.manager.liquibase.directory=F:/Theta/ctbctw/liquibase/yamls
liquibase.home.directory=F:/Theta/ctbctw/liquibase