### Configure Spring Boot for JavaFX (disable server mode)
spring.main.web-application-type=none
### General
spring.application.name=Liquibase Uploader

### File Manager Configuration
file.manager.project.directory=./project
file.manager.liquibase.directory=./liquibase
file.manager.allowed.extensions=.yaml,.sqlx

# Predefined modules (comma-separated)
file.manager.modules=bjr,cis,col,lac,lms,ibdm,exr

# Default versions (comma-separated)
file.manager.default.versions=9.0.0.9,9.0.0.10

# Script executor
file.manager.script.executor.command=cmd
liquibase.home.directory=F:/Theta/ctbctw/liquibase
